"""
QAYAMAT — Submission-ready reports (HackerOne / Bugcrowd / Markdown).
"""

from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional
from urllib.parse import urlparse
from core.repro_steps import enrich_finding_with_steps


SEVERITY_MAP_H1 = {
    "Critical": "critical",
    "High": "high",
    "Medium": "medium",
    "Low": "low",
    "Info": "none",
}


class SubmissionReportBuilder:
    def __init__(self, findings: List[dict], program: str = ""):
        self.findings = findings
        self.program = program

    def _redact(self, text: str) -> str:
        import re
        text = re.sub(r"(?i)(api[_-]?key|token|password|secret)\s*[:=]\s*\S+", r"\1=[REDACTED]", text or "")
        return text

    def build_markdown(self, finding: dict, platform: str = "hackerone") -> str:
        f = enrich_finding_with_steps(dict(finding))
        sev = f.get("severity", "Medium")
        url = f.get("url", "")
        host = urlparse(url).netloc or url
        repro = f.get("reproduction_markdown", "")
        md = f"""# {f.get('title', 'Security Vulnerability')}

## Summary
{self._redact(f.get('description', ''))}

## Severity
**{sev}** ({SEVERITY_MAP_H1.get(sev, 'medium')} for {platform})

## Affected asset
`{host}`

{repro}

## Proof of Concept
```
{self._redact(str(f.get('evidence', ''))[:2000])}
```

## References
- Scanner: {f.get('tool', 'qayamat')}
- Template: {f.get('template', 'n/a')}
- CVE: {f.get('cve', [])}
- Validation score: {f.get('validation_score', 'n/a')}

---
*Generated by QAYAMAT — {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*
"""
        return md

    def export_all(self, output_dir: str = "reports/submissions", platform: str = "hackerone") -> List[str]:
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        paths = []
        for i, f in enumerate(self.findings):
            if f.get("triage_status") in ("false_positive", "duplicate", "rejected"):
                continue
            slug = "".join(c if c.isalnum() else "_" for c in f.get("title", "finding")[:40])
            path = out / f"{i+1:03d}_{slug}_{platform}.md"
            path.write_text(self.build_markdown(f, platform), encoding="utf-8")
            paths.append(str(path))
        index = out / "INDEX.md"
        index.write_text(
            "\n".join(f"- [{Path(p).name}]({Path(p).name})" for p in paths),
            encoding="utf-8",
        )
        paths.append(str(index))
        return paths

    def build_bugcrowd_json(self, finding: dict) -> dict:
        return {
            "title": finding.get("title", ""),
            "severity": SEVERITY_MAP_H1.get(finding.get("severity", "Medium"), "medium"),
            "vulnerability_type": finding.get("vuln_type", "other"),
            "description": self._redact(finding.get("description", "")),
            "proof_of_concept": self._redact(str(finding.get("evidence", ""))[:2000]),
            "url": finding.get("url", ""),
        }
